export const Operations = {
  Count: 'count',
  CountDocuments: 'countDocuments',
  EstimatedDocumentCount: 'estimatedDocumentCount',
  Find: 'find',
  FindOne: 'findOne',
  FindOneAndUpdate: 'findOneAndUpdate',
  FindOneAndRemove: 'findOneAndRemove',
  FindOneAndDelete: 'findOneAndDelete',
  Update: 'update',
  UpdateOne: 'updateOne',
  UpdateMany: 'updateMany',
  DeleteOne: 'deleteOne',
  DeleteMany: 'deleteMany',
};
